# Mean Normalization

In machine learning we use large amounts of data to train our models. Some machine learning algorithms may require that the data is *normalized* in order to work correctly. The idea of normalization, also known as *feature scaling*, is to ensure that all the data is on a similar scale, *i.e.* that all the data takes on a similar range of values. For example, we might have a dataset that has values between 0 and 5,000. By normalizing the data we can make the range of values be between 0 and 1.

In this lab, you will be performing a different kind of feature scaling known as *mean normalization*. Mean normalization will scale the data, but instead of making the values be between 0 and 1, it will distribute the values evenly in some small interval around zero. For example, if we have a dataset that has values between 0 and 5,000, after mean normalization the range of values will be distributed in some small range around 0, for example between -3 to 3. Because the range of values are distributed evenly around zero, this guarantees that the average (mean) of all elements will be zero. Therefore, when you perform *mean normalization* your data will not only be scaled but it will also have an average of zero. 

# To Do:

You will start by importing NumPy and creating a rank 2 ndarray of random integers between 0 and 5,000 (inclusive) with 1000 rows and 20 columns. This array will simulate a dataset with a wide range of values. Fill in the code below

In [13]:
# import NumPy into Python
import numpy as np;

# Create a 1000 x 20 ndarray with random integers in the half-open interval [0, 5001).
X = np.linspace(0,5000,20000, endpoint=True).reshape(1000,20)
# print the shape of X
print(X.shape)

(1000, 20)


Now that you created the array we will mean normalize it. We will perform mean normalization using the following equation:

$\mbox{Norm_Col}_i = \frac{\mbox{Col}_i - \mu_i}{\sigma_i}$

where $\mbox{Col}_i$ is the $i$th column of $X$, $\mu_i$ is average of the values in the $i$th column of $X$, and $\sigma_i$ is the standard deviation of the values in the $i$th column of $X$. In other words, mean normalization is performed by subtracting from each column of $X$ the average of its values, and then by dividing by the standard deviation of its values. In the space below, you will first calculate the average and standard deviation of each column of $X$. 

In [14]:
# Average of the values in each column of X
ave_cols = X.mean(axis = 0)

# Standard Deviation of the values in each column of X
std_cols = X.std(axis = 0)

If you have done the above calculations correctly, then `ave_cols` and `std_cols`, should both be vectors with shape `(20,)` since $X$ has 20 columns. You can verify this by filling the code below:

In [15]:
# Print the shape of ave_cols
print(ave_cols.shape)

# Print the shape of std_cols
print(std_cols.shape)

(20,)
(20,)


You can now take advantage of Broadcasting to calculate the mean normalized version of $X$ in just one line of code using the equation above. Fill in the code below

In [16]:
# Mean normalize X
X_norm =  X - ave_cols / std_cols

If you have performed the mean normalization correctly, then the average of all the elements in $X_{\tiny{\mbox{norm}}}$ should be close to zero, and they should be evenly distributed in some small interval around zero. You can verify this by filing the code below:

In [19]:
# Print the average of all the values of X_norm
print(X_norm.mean())

# Print the average of the minimum value in each column of X_norm
print(X_norm.min(axis = 0))

# Print the average of the maximum value in each column of X_norm
print(X_norm.max(axis = 0))

2498.268034928989
[-1.73031962 -1.48048033 -1.23064103 -0.98080174 -0.73096244 -0.48112314
 -0.23128385  0.01855545  0.26839474  0.51823404  0.76807333  1.01791263
  1.26775192  1.51759122  1.76743051  2.01726981  2.26710911  2.5169484
  2.7667877   3.01662699]
[4993.51944287 4993.76928216 4994.01912146 4994.26896075 4994.51880005
 4994.76863934 4995.01847864 4995.26831793 4995.51815723 4995.76799653
 4996.01783582 4996.26767512 4996.51751441 4996.76735371 4997.017193
 4997.2670323  4997.51687159 4997.76671089 4998.01655018 4998.26638948]


You should note that since $X$ was created using random integers, the above values will vary. 

# Data Separation

After the data has been mean normalized, it is customary in machine learnig to split our dataset into three sets:

1. A Training Set
2. A Cross Validation Set
3. A Test Set

The dataset is usually divided such that the Training Set contains 60% of the data, the Cross Validation Set contains 20% of the data, and the Test Set contains 20% of the data. 

In this part of the lab you will separate `X_norm` into a Training Set, Cross Validation Set, and a Test Set. Each data set will contain rows of `X_norm` chosen at random, making sure that we don't pick the same row twice. This will guarantee that all the rows of `X_norm` are chosen and randomly distributed among the three new sets.

You will start by creating a rank 1 ndarray that contains a random permutation of the row indices of `X_norm`. You can do this by using the `np.random.permutation()` function. The `np.random.permutation(N)` function creates a random permutation of integers from 0 to `N - 1`. Let's see an example:

In [3]:
# We create a random permutation of integers 0 to 4
import numpy as np
np.random.permutation(5)#like arange but not in order

array([1, 4, 2, 0, 3])

In [4]:
np.arange(5)

array([0, 1, 2, 3, 4])

# To Do

In the space below create a rank 1 ndarray that contains a random permutation of the row indices of `X_norm`. You can do this in one line of code by extracting the number of rows of `X_norm` using the `shape` attribute and then passing it to the  `np.random.permutation()` function. Remember the `shape` attribute returns a tuple with two numbers in the form `(rows,columns)`.

In [6]:
# Create a rank 1 ndarray that contains a random permutation of the row indices of `X_norm`
row_indices =np.random.permutation(1000)#numbers from 0 to 999 not in order
row_indices[0:600]

array([547, 893, 531, 175, 270, 529, 980, 983, 412, 442, 645, 460, 135,
       329, 179, 191, 532, 154, 794, 282, 365,  68, 876, 216, 473, 246,
       650, 871, 827, 185,  49,  27, 864, 126,  46, 752, 560, 935, 403,
       255, 898,  37, 773, 748,  87, 850, 120, 824, 223, 276, 939, 878,
       443, 638, 632, 741, 197, 128, 198, 789, 754, 572, 973, 891, 503,
       570, 813, 482, 806, 923, 662, 310,   3, 545, 149, 880, 776, 124,
       680, 884, 865, 260, 870, 341, 930, 130, 979, 924, 770, 823, 283,
       431, 257, 745, 743, 606, 666, 802, 996,   9, 134, 384, 914, 699,
       469, 896,  48, 882, 493, 855, 101, 288, 202, 931, 685,  66, 712,
       575,  62, 145, 846, 510,  12, 552, 915, 426, 507, 746, 751, 119,
        39, 358, 577, 703, 603, 908, 112,  83, 816, 627, 728, 474, 897,
       702, 558, 610, 778, 332, 663,  15, 118, 307, 399, 414, 352, 306,
       854, 402, 252,  84,   8, 345, 637, 546, 324, 517, 404, 861, 234,
       584, 819, 240, 933, 833, 433, 446, 739, 982,  38,  56, 98

Now you can create the three datasets using the `row_indices` ndarray to select the rows that will go into each dataset. Rememeber that the Training Set contains 60% of the data, the Cross Validation Set contains 20% of the data, and the Test Set contains 20% of the data. Each set requires just one line of code to create. Fill in the code below

In [28]:
# Make any necessary calculations.
# You can save your calculations into variables to use later.
row_indices = np.random.permutation(X_norm)

# Create a Training Set
X_train = row_indices[0:12000]

# Create a Cross Validation Set
X_crossVal = row_indices[12000:16000] 

# Create a Test Set
X_test = row_indices[16000:20000]

If you performed the above calculations correctly, then `X_tain` should have 600 rows and 20 columns, `X_crossVal` should have 200 rows and 20 columns, and `X_test` should have 200 rows and 20 columns. You can verify this by filling the code below:

In [30]:
# Print the shape of X_train
print(X_train.shape)

# Print the shape of X_crossVal
print(X_crossVal.shape)

# Print the shape of X_test
print(X_test.shape)

(1000, 20)
(0, 20)
(0, 20)
