# Boolean Indexing, Set Operations, and Sorting

   ##                                 Boolean indexing

In [13]:
import numpy as np
# We create a 5 x 5 ndarray that contains integers from 0 to 24
X = np.arange(25).reshape(5, 5)

# We print X
print()
print('Original X = \n', X)
print()

# We use Boolean indexing to select elements in X:
print('The elements in X that are greater than 10:', X[X > 10])
print('The elements in X that less than or equal to 7:', X[X <= 7])
print('The elements in X that are between 10 and 17:', X[(X > 10) & (X < 17)])# llogical and [() & ()]  logical or  [() | ()]
print('The elements in X that are less than 10 or greater than 17:', X[(X < 10) | (X > 17)])
# We use Boolean indexing to assign the elements that are between 10 and 17 the value of -1
X[(X > 10) & (X < 17)] = -1

# We print X
print()
print('X = \n', X)
print()


Original X = 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]

The elements in X that are greater than 10: [11 12 13 14 15 16 17 18 19 20 21 22 23 24]
The elements in X that less than or equal to 7: [0 1 2 3 4 5 6 7]
The elements in X that are between 10 and 17: [11 12 13 14 15 16]
The elements in X that are less than 10 or greater than 17: [ 0  1  2  3  4  5  6  7  8  9 18 19 20 21 22 23 24]

X = 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 -1 -1 -1 -1]
 [-1 -1 17 18 19]
 [20 21 22 23 24]]



# using nest for loop in list 

In [1]:
x=[[1,2,3],[4,5,6],[7,8,9]]
for i in range(0,len(x)):
    for j in range(0,len(x[i])):
        if x[i][j] > 5 and x[i][j] < 9:
            x[i][j]=-1
print(x)
    

[[1, 2, 3], [4, 5, -1], [-1, -1, 9]]


## Set operations and comparing two arrays

In [4]:
# We create a rank 1 ndarray
x = np.array([1,2,3,4,5])

# We create a rank 1 ndarray
y = np.array([6,7,2,8,4])

# We print x
print()
print('x = ', x)

# We print y
print()
print('y = ', y)

# We use set operations to compare x and y:
print()
print('The elements that are both in x and y:', np.intersect1d(x,y))
print('The elements that are in x that are not in y:', np.setdiff1d(x,y))
print('The elements that are in y that are not in x:', np.setdiff1d(y,x))
print('All the elements of x and y:',np.union1d(x,y))


x =  [1 2 3 4 5]

y =  [6 7 2 8 4]

The elements that are both in x and y: [2 4]
The elements that are in x that are not in y: [1 3 5]
The elements that are in y that are not in x: [6 7 8]
All the elements of x and y: [1 2 3 4 5 6 7 8]


## Sorting using sort function

In [6]:
# We create an unsorted rank 1 ndarray
x = np.random.randint(1,12,size=(10,))

# We print x
print()
print('Original x = ', x)

# We sort x and print the sorted array using sort as a function.
print()
print('Sorted x (out of place):', np.sort(x))#for inplace x=np.sort(x)

# When we sort out of place the original array remains intact. To see this we print x again
print()
print('x after sorting:', x)




Original x =  [ 2  4  5  8 11  4 10  8  6  7]

Sorted x (out of place): [ 2  4  4  5  6  7  8  8 10 11]

x after sorting: [ 2  4  5  8 11  4 10  8  6  7]


## Sorting using sort method

In [8]:
# We create an unsorted rank 1 ndarray
x = np.random.randint(1,11,size=(10,))

# We print x
print()
print('Original x = ', x)

# We sort x and print the sorted array using sort as a method.
x.sort()#inplace

# When we sort in place the original array is changed to the sorted array. To see this we print x again
print()
print('x after sorting (inplace):', x)


Original x =  [5 5 7 9 6 6 7 2 2 5]

x after sorting (inplace): [2 2 5 5 5 6 6 7 7 9]


# Sorting 2D array by columns and rows

In [10]:
# We create an unsorted rank 2 ndarray
X = np.random.randint(1,11,size=(5,5))

# We print X
print()
print('Original X = \n', X)
print()

# We sort the columns of X and print the sorted array
print()
print('X with sorted columns :\n', np.sort(X, axis = 0))

# We sort the rows of X and print the sorted array
print()
print('X with sorted rows :\n', np.sort(X, axis = 1))


Original X = 
 [[ 9  2 10  5  7]
 [ 9  2 10  8  4]
 [ 8 10  2  3  6]
 [ 8  2  8  9 10]
 [ 3  3  7  9  9]]


X with sorted columns :
 [[ 3  2  2  3  4]
 [ 8  2  7  5  6]
 [ 8  2  8  8  7]
 [ 9  3 10  9  9]
 [ 9 10 10  9 10]]

X with sorted rows :
 [[ 2  5  7  9 10]
 [ 2  4  8  9 10]
 [ 2  3  6  8 10]
 [ 2  8  8  9 10]
 [ 3  3  7  9  9]]


## Numpy_quiz_Manipulating_ndarrays

In [12]:
import numpy as np

# Create a 5 x 5 ndarray with consecutive integers from 1 to 25 (inclusive).
arr = np.arange(1, 26).reshape(5, 5)

# Afterwards use Boolean indexing to pick out only the odd numbers in the array
oddArr = arr[arr%2 != 0]

print('\nThe elements in the array \'arr\': \n', arr)

print('\nThe elements in the array \'arr\' that are odd: ', oddArr)


The elements in the array 'arr': 
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]

The elements in the array 'arr' that are odd:  [ 1  3  5  7  9 11 13 15 17 19 21 23 25]


In [11]:
x=5
x%2

1

In [12]:
x=6
x%2

0

In [13]:
x=5
if x%2 !=0:
    print("odd")
else:
    print("even")

odd


In [14]:
x=6
if x%2 !=0:
    print("odd")
else:
    print("even")

even
