# Numpy 

In [1]:
import numpy as np
# install  :    pip install numpy         (for any device)
# install :     conda install numpy    only for anaconda   

 #                        How to create a numpy 1D array?


In [4]:
# We import NumPy into Python
import numpy as np

# We create a 1D ndarray that contains only integers
x = np.array([1, 2, 3, 4, 5])

# Let's print the ndarray we just created using the print() command
print('x = ', x)
print(type(x))

x =  [1 2 3 4 5]
<class 'numpy.ndarray'>


In [5]:

print('The elements in x are of type:', x.dtype)

The elements in x are of type: int32


In [6]:
print('x has dimensions:', x.shape)#the output is a tuple from one element

x has dimensions: (5,)


# How to create a numpy 2D array?

In [7]:
# We create a rank 2 ndarray that only contains integers
#                0       1       2         3  
#              0 1 2   0 1 2   0 1 2    0   1  2
Y = np.array([[1,2,3],[4,5,6],[7,8,9], [10,11,12]])

# We print Y
print()#\n
print('Y = \n', Y)
print()#\n
# We print information about Y
print('Y has dimensions:', Y.shape)
print('Y has a total of', Y.size, 'elements')
print('Y is an object of type:', type(Y))
print('The elements in Y are of type:', Y.dtype)


Y = 
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

Y has dimensions: (4, 3)
Y has a total of 12 elements
Y is an object of type: <class 'numpy.ndarray'>
The elements in Y are of type: int32


# How to create a string 1D array ?

In [8]:
# We create a rank 1 ndarray that only contains strings
x = np.array(['Hello', 'World'])

# We print x
print('x = ', x)
# We print information about x
print('x has dimensions:', x.shape)
print('x is an object of type:', type(x))
print('The elements in x are of type:', x.dtype)

x =  ['Hello' 'World']
x has dimensions: (2,)
x is an object of type: <class 'numpy.ndarray'>
The elements in x are of type: <U5


#### to read more abut numpy data type you can use this link :
https://docs.scipy.org/doc/numpy-1.13.0/user/basics.types.html

# Create a String and int in 1D array

In [9]:
# We create a rank 1 ndarray from a Python list that contains integers and strings
x = np.array([1, 2, 'World'])

# We print the ndarray
print('x = ', x)
print("\n")

# We print information about x
print('x has dimensions:', x.shape)
print('x is an object of type:', type(x))
print('The elements in x are of type:', x.dtype)

x =  ['1' '2' 'World']


x has dimensions: (3,)
x is an object of type: <class 'numpy.ndarray'>
The elements in x are of type: <U11


# Create a float and int in 1D array (upcasting)

In [10]:
# We create a rank 1 ndarray that contains integers
x = np.array([1,2,3])
print("x=",x)
# We create a rank 1 ndarray that contains floats
y = np.array([1.0,2.0,3.0])
print("y=",y)
# We create a rank 1 ndarray that contains integers and floats
z = np.array([1, 2.5, 4])
print("z=",z)
# We print the dtype of each ndarray
print('The elements in x are of type:', x.dtype)
print('The elements in y are of type:', y.dtype)
print('The elements in z are of type:', z.dtype)

x= [1 2 3]
y= [1. 2. 3.]
z= [1.  2.5 4. ]
The elements in x are of type: int32
The elements in y are of type: float64
The elements in z are of type: float64


# Create a float and int in 1D array (upcasting with int)

In [11]:
# We create a rank 1 ndarray of floats but set the dtype to int64
x = np.array([1.5, 2.2, 3.7, 4.0, 5.9], dtype = np.int32)

# We print x
print()
print('x = ', x)
print()

# We print the dtype x
print('The elements in x are of type:', x.dtype)


x =  [1 2 3 4 5]

The elements in x are of type: int32


In [25]:
x = np.array([1.5, 2.2, 3.7, 4.0, 5.9])

# We print x
print()
print('x = ', x)
print()

# We print the dtype x
print('The elements in x are of type:', x.dtype)


x =  [1.5 2.2 3.7 4.  5.9]

The elements in x are of type: float64
